// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShaloTrack_API.Data;

#nullable disable

namespace ShaloTrack_API.Migrations
{
    [DbContext(typeof(ShaloTrackDbContext))]
    [Migration("20260715082041_AddLocationUpdateTrigger")]
    partial class AddLocationUpdateTrigger
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ShaloTrack_API.Models.CurrentLocation", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Heading")
                        .HasColumnType("numeric");

                    b.Property<bool>("IgnitionStatus")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<bool>("MovementStatus")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Speed")
                        .HasColumnType("numeric");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("DeviceId");

                    b.HasIndex("VehicleId")
                        .IsUnique();

                    b.ToTable("CurrentLocations");
                });

            modelBuilder.Entity("ShaloTrack_API.Models.Customer", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("integer");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirebaseUid")
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NicNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileImage")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CustomerId");

                    b.HasIndex("FirebaseUid")
                        .IsUnique();

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("ShaloTrack_API.Models.DeviceAssignment", b =>
                {
                    b.Property<Guid>("AssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("RemovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("AssignmentId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("VehicleId");

                    b.ToTable("DeviceAssignments");
                });

            modelBuilder.Entity("ShaloTrack_API.Models.DeviceEvent", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("EventId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<string>("Metadata")
                        .HasColumnType("text");

                    b.Property<long?>("RawPacketId")
                        .HasColumnType("bigint");

                    b.Property<short>("Severity")
                        .HasColumnType("smallint");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uuid");

                    b.HasKey("EventId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("RawPacketId");

                    b.HasIndex("VehicleId");

                    b.ToTable("DeviceEvents");
                });

            modelBuilder.Entity("ShaloTrack_API.Models.DeviceStatus", b =>
                {
                    b.Property<long>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("StatusId"));

                    b.Property<int>("BatteryLevel")
                        .HasColumnType("integer");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<int>("GpsSignal")
                        .HasColumnType("integer");

                    b.Property<bool>("IgnitionStatus")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOnline")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastHeartbeat")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("MovementStatus")
                        .HasColumnType("boolean");

                    b.Property<int>("PowerStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("StatusId");

                    b.HasIndex("DeviceId")
                        .IsUnique();

                    b.ToTable("DeviceStatuses");
                });

            modelBuilder.Entity("ShaloTrack_API.Models.GpsDevice", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActivationStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirmwareVersion")
                        .HasColumnType("text");

                    b.Property<string>("ImeiNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("InstalledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NetworkProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProtocolType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SimNumber")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("WarrantyExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("DeviceId");

                    b.ToTable("GpsDevices");
                });

            modelBuilder.Entity("ShaloTrack_API.Models.GpsTracking", b =>
                {
                    b.Property<long>("TrackingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TrackingId"));

                    b.Property<decimal?>("Altitude")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EventTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("GpsAccuracy")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Heading")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("numeric");

                    b.Property<int>("Satellites")
                        .HasColumnType("integer");

                    b.Property<decimal>("Speed")
                        .HasColumnType("numeric");

                    b.HasKey("TrackingId");

                    b.HasIndex("DeviceId");

                    b.ToTable("GpsTrackings");
                });

            modelBuilder.Entity("ShaloTrack_API.Models.RawPacket", b =>
                {
                    b.Property<long>("PacketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("PacketId"));

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid");

                    b.Property<int>("PacketLength")
                        .HasColumnType("integer");

                    b.Property<bool>("Parsed")
                        .HasColumnType("boolean");

                    b.Property<string>("ProtocolNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawHex")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ReceivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PacketId");

                    b.HasIndex("DeviceId");

                    b.ToTable("RawPackets");
                });

            modelBuilder.Entity("ShaloTrack_API.Models.Vehicle", b =>
                {
                    b.Property<Guid>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChassisNumber")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("EngineNumber")
                        .HasColumnType("text");

                    b.Property<string>("FuelType")
                        .HasColumnType("text");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VehicleNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VehicleType")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("VehicleId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("ShaloTrack_API.Models.CurrentLocation", b =>
                {
                    b.HasOne("ShaloTrack_API.Models.GpsDevice", "Device")
                        .WithOne("CurrentLocation")
                        .HasForeignKey("ShaloTrack_API.Models.CurrentLocation", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShaloTrack_API.Models.Vehicle", "Vehicle")
                        .WithOne("CurrentLocation")
                        .HasForeignKey("ShaloTrack_API.Models.CurrentLocation", "VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ShaloTrack_API.Models.DeviceAssignment", b =>
                {
                    b.HasOne("ShaloTrack_API.Models.GpsDevice", "Device")
                        .WithMany("DeviceAssignments")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShaloTrack_API.Models.Vehicle", "Vehicle")
                        .WithMany("DeviceAssignments")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ShaloTrack_API.Models.DeviceEvent", b =>
                {
                    b.HasOne("ShaloTrack_API.Models.GpsDevice", "Device")
                        .WithMany("DeviceEvents")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShaloTrack_API.Models.RawPacket", "RawPacket")
                        .WithMany("DeviceEvents")
                        .HasForeignKey("RawPacketId");

                    b.HasOne("ShaloTrack_API.Models.Vehicle", "Vehicle")
                        .WithMany("DeviceEvents")
                        .HasForeignKey("VehicleId");

                    b.Navigation("Device");

                    b.Navigation("RawPacket");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("ShaloTrack_API.Models.DeviceStatus", b =>
                {
                    b.HasOne("ShaloTrack_API.Models.GpsDevice", "Device")
                        .WithOne()
                        .HasForeignKey("ShaloTrack_API.Models.DeviceStatus", "DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("ShaloTrack_API.Models.GpsTracking", b =>
                {
                    b.HasOne("ShaloTrack_API.Models.GpsDevice", "Device")
                        .WithMany("GpsTrackings")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("ShaloTrack_API.Models.RawPacket", b =>
                {
                    b.HasOne("ShaloTrack_API.Models.GpsDevice", "Device")
                        .WithMany("RawPackets")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Device");
                });

            modelBuilder.Entity("ShaloTrack_API.Models.Vehicle", b =>
                {
                    b.HasOne("ShaloTrack_API.Models.Customer", "Customer")
                        .WithMany("Vehicles")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ShaloTrack_API.Models.Customer", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("ShaloTrack_API.Models.GpsDevice", b =>
                {
                    b.Navigation("CurrentLocation");

                    b.Navigation("DeviceAssignments");

                    b.Navigation("DeviceEvents");

                    b.Navigation("GpsTrackings");

                    b.Navigation("RawPackets");
                });

            modelBuilder.Entity("ShaloTrack_API.Models.RawPacket", b =>
                {
                    b.Navigation("DeviceEvents");
                });

            modelBuilder.Entity("ShaloTrack_API.Models.Vehicle", b =>
                {
                    b.Navigation("CurrentLocation");

                    b.Navigation("DeviceAssignments");

                    b.Navigation("DeviceEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
